/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ParentDashboardRouteImport } from './routes/parent-dashboard'
import { Route as ModeratorRouteImport } from './routes/moderator'

import { Route as HeroDemoRouteImport } from './routes/hero-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LevelsIndexRouteImport } from './routes/levels/index'
import { Route as LectureLectureIdRouteImport } from './routes/lecture.$lectureId'
import { Route as ExamLevelIdRouteImport } from './routes/exam.$levelId'
import { Route as LevelsClassroomLevelIdRouteImport } from './routes/levels/classroom/$levelId'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent-dashboard',
  path: '/parent-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorRoute = ModeratorRouteImport.update({
  id: '/moderator',
  path: '/moderator',
  getParentRoute: () => rootRouteImport,
} as any)

const HeroDemoRoute = HeroDemoRouteImport.update({
  id: '/hero-demo',
  path: '/hero-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsIndexRoute = LevelsIndexRouteImport.update({
  id: '/levels/',
  path: '/levels/',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureLectureIdRoute = LectureLectureIdRouteImport.update({
  id: '/lecture/$lectureId',
  path: '/lecture/$lectureId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamLevelIdRoute = ExamLevelIdRouteImport.update({
  id: '/exam/$levelId',
  path: '/exam/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsClassroomLevelIdRoute = LevelsClassroomLevelIdRouteImport.update({
  id: '/levels/classroom/$levelId',
  path: '/levels/classroom/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hero-demo': typeof HeroDemoRoute

  '/moderator': typeof ModeratorRoute
  '/parent-dashboard': typeof ParentDashboardRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/exam/$levelId': typeof ExamLevelIdRoute
  '/lecture/$lectureId': typeof LectureLectureIdRoute
  '/levels/': typeof LevelsIndexRoute
  '/levels/classroom/$levelId': typeof LevelsClassroomLevelIdRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hero-demo': typeof HeroDemoRoute

  '/moderator': typeof ModeratorRoute
  '/parent-dashboard': typeof ParentDashboardRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/exam/$levelId': typeof ExamLevelIdRoute
  '/lecture/$lectureId': typeof LectureLectureIdRoute
  '/levels': typeof LevelsIndexRoute
  '/levels/classroom/$levelId': typeof LevelsClassroomLevelIdRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hero-demo': typeof HeroDemoRoute

  '/moderator': typeof ModeratorRoute
  '/parent-dashboard': typeof ParentDashboardRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/exam/$levelId': typeof ExamLevelIdRoute
  '/lecture/$lectureId': typeof LectureLectureIdRoute
  '/levels/': typeof LevelsIndexRoute
  '/levels/classroom/$levelId': typeof LevelsClassroomLevelIdRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hero-demo'
    | '/moderator'
    | '/parent-dashboard'
    | '/profile'
    | '/sitemap.xml'
    | '/exam/$levelId'
    | '/lecture/$lectureId'
    | '/levels/'
    | '/levels/classroom/$levelId'
    | '/terms-of-service'
    | '/privacy-policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hero-demo'
    | '/moderator'
    | '/parent-dashboard'
    | '/profile'
    | '/sitemap.xml'
    | '/exam/$levelId'
    | '/lecture/$lectureId'
    | '/levels'
    | '/levels/classroom/$levelId'
    | '/terms-of-service'
    | '/privacy-policy'
  id:
    | '__root__'
    | '/'
    | '/hero-demo'
    | '/moderator'
    | '/parent-dashboard'
    | '/profile'
    | '/sitemap.xml'
    | '/exam/$levelId'
    | '/lecture/$lectureId'
    | '/levels/'
    | '/levels/classroom/$levelId'
    | '/terms-of-service'
    | '/privacy-policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeroDemoRoute: typeof HeroDemoRoute
  ModeratorRoute: typeof ModeratorRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ExamLevelIdRoute: typeof ExamLevelIdRoute
  LectureLectureIdRoute: typeof LectureLectureIdRoute
  LevelsIndexRoute: typeof LevelsIndexRoute
  LevelsClassroomLevelIdRoute: typeof LevelsClassroomLevelIdRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator': {
      id: '/moderator'
      path: '/moderator'
      fullPath: '/moderator'
      preLoaderRoute: typeof ModeratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-dashboard': {
      id: '/parent-dashboard'
      path: '/parent-dashboard'
      fullPath: '/parent-dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-demo': {
      id: '/hero-demo'
      path: '/hero-demo'
      fullPath: '/hero-demo'
      preLoaderRoute: typeof HeroDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/': {
      id: '/levels/'
      path: '/levels'
      fullPath: '/levels/'
      preLoaderRoute: typeof LevelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture/$lectureId': {
      id: '/lecture/$lectureId'
      path: '/lecture/$lectureId'
      fullPath: '/lecture/$lectureId'
      preLoaderRoute: typeof LectureLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$levelId': {
      id: '/exam/$levelId'
      path: '/exam/$levelId'
      fullPath: '/exam/$levelId'
      preLoaderRoute: typeof ExamLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/classroom/$levelId': {
      id: '/levels/classroom/$levelId'
      path: '/levels/classroom/$levelId'
      fullPath: '/levels/classroom/$levelId'
      preLoaderRoute: typeof LevelsClassroomLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeroDemoRoute: HeroDemoRoute,
  ModeratorRoute: ModeratorRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ExamLevelIdRoute: ExamLevelIdRoute,
  LectureLectureIdRoute: LectureLectureIdRoute,
  LevelsIndexRoute: LevelsIndexRoute,
  LevelsClassroomLevelIdRoute: LevelsClassroomLevelIdRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
